apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: amberapp-system
type: Opaque
stringData:
  username: admin
  password: password
---
apiVersion: storage.jibudata.com/v1alpha1
kind: AppHook
metadata:
  name: mongo-sample
  namespace: amberapp-system
spec:
  name: mongo-sample
  appProvider: mongodb
  endPoint: "mongodb.mongodb-ns"
  secret: 
    name: mongo-secret
    namespace: "amberapp-system"
